import Footer from "../Home/Footer";
const Privacy=()=>{
    return(
    
    <>
    <section class="page-header bg_img oh" data-background="assets/images/banner/banner-bg-7.jpg">

<div class="bottom-shape d-none d-md-block">

    <img src="assets/images/banner/banner-bg-7.jpg" alt="css"/>

</div>

<div class="page-left-thumb">

    <img src="assets/images/bg/privacy-header.png" alt="bg"/>

</div>

<div class="container">

    <div class="page-header-content ">

        <h2 class="title">Our Privacy Policy</h2>

        <ul class="breadcrumb">

            <li>

                <a href="index.html">Home</a>

            </li>

            <li>

                Privacy

            </li>

        </ul>

    </div>

</div>

</section>









<section class="privacy-section padding-bottom">

<div class="container">

    <div class="row justify-content-center">

        <div class="col-lg-8">

            <div class="section-header">

                <h2 class="title">Privacy Policy</h2>

                <p>Please read this Privacy Policy carefully before using this website</p>

            </div>

        </div>

    </div>

    <div class="row justify-content-between">

        <div class="col-lg-4">

            <aside class="sticky-menu">

                <div class="faq-menu bg_img" data-background="https://thecareerads.com/assets/images/faq/faq-menu.png">

                    <ul id="faq-menu">

                        <li class="nav-item">

                            <a class="nav-link" href="#general">Cookie</a>                                 

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#prop">Company</a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#secu">Country</a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#info">Customer</a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#cooki">Device</a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#ipaddr">IP Address</a>

                        </li>

                         <li class="nav-item">

                            <a class="nav-link" href="#prsonnel">Personnel</a>

                        </li>

                         <li class="nav-item">

                            <a class="nav-link" href="#personal">Personal Data</a>

                        </li>

                         <li class="nav-item">

                            <a class="nav-link" href="#services">Services</a>

                        </li>

                         <li class="nav-item">

                            <a class="nav-link" href="#tps">Third Party Services</a>

                        </li>

                         <li class="nav-item">

                            <a class="nav-link" href="#website">Website</a>

                        </li>

                         <li class="nav-item">

                            <a class="nav-link" href="#yous">You</a>

                        </li>

                        

                    </ul>

                </div>

            </aside>

        </div>

        <div class="col-lg-8 col-xl-7 text-justify">

            <article class="mt-70 mt-lg-0">

                <div class="privacy-item">

                      <p>

                        The Career Ads. (we," "our," or us") is committed to protecting your privacy. This Privacy Policy explsins how your personal information is collected, used, and disclosed by The Career Ads.

                    </p>

                    <p>

                        This Privacy Policy applies to our application named The Career Ads , and its assoziated subdomains (collectively, ur "Service". By sccessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as descrited inthis Privacy Policy and our Terms of Service.

                    </p>

                </div>

                <div class="privacy-item" id="general">

                  

                    <h3 class="title">Definitions And Key Terms</h3>

                    <h5 class="title">Cookie</h5>

                    <p>Small amount of data generated by a website and saved by your web browser. Its used to identiy your browser provide analytics, remember information about you such as your language preference or login information.</p>

                  

                </div>

                <div class="privacy-item" id="prop">

                    <h3 class="title">Company</h3>

                    <p>when this policy mentions “Company,” we,” “us,” or “out,” it refers to The Career Ads that is responsible for your information under this Privacy Policy.</p>

                </div>

                <div class="privacy-item" id="secu">

                    <h3 class="title">Country</h3>

                    <p>where The Career Ads or the ownerstfounders of The Career Ads are based, inthis case i India,</p>

                </div>

                <div class="privacy-item" id="info">

                    <h3 class="title">Customer</h3>

                    <p> refers tothe company, organization or person that signs up to use the The Career Ads Service to manage the relationships with your consumers or service users.</p>

                </div>

                <div class="privacy-item" id="cooki">

                    <h3 class="title">Device</h3>

                    <p>any intemet connected device such as 2 phone, tablet, computer or any other device that can be used to visit The Career Ads and use the services.</p>

                </div>

                <div class="privacy-item" id="ipaddr">

                    <h3 class="title">IP Address</h3>

                    <p>Every device connected to the Internets assigned 3 number known 2s an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which 2 device is connecting to the Intemet.</p>

                </div>

                 <div class="privacy-item" id="prsonnel">

                    <h3 class="title">Personnel</h3>

                    <p>Refers to those individuals who are employed by The Career Ads or are under contract to perform a service on behatf of one ofthe parties.</p>

                </div>

                 <div class="privacy-item" id="personal">

                    <h3 class="title">Personal Data</h3>

                    <p>any information that directly indirectly, orn connection wth other information — including a personal identification number — allows forthe identification or identiiablty of natural person.</p>

                </div>

                 <div class="privacy-item" id="services">

                    <h3 class="title">Services</h3>

                    <p>refers tothe service provided by The Cateer Ads as described in the relative terms (if available) and on tis platform.</p>

                </div>

                 <div class="privacy-item" id="tps">

                    <h3 class="title">Third Party Service</h3>

                    <p> refers to edvertsers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you

                    </p>

                </div>

                 <div class="privacy-item" id="website">

                    <h3 class="title">Website</h3>

                    <p>The Career Ads's site, which can be accessed va this URL: ___________________</p>

                </div>

                <div class="privacy-item" id="yous">

                    <h3 class="title">You</h3>

                    <p> A person or entity that is registered with The Career Ads to use the Services.</p>

                </div>

                <div class="privacy-item" id="ipaddr">

                    <h3 class="title">Third Party Services</h3>

                    <p> 

We may display, include or make available third-party content (including data, information, applications and other products services) (or provide links to third-party websites or services ("Third- Party Services)</p>

<p>You acknowledge snd saree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, valcty, copyright compliance, legality, decency, quslty or any other aspect thereof. We do not assume and shall not have any liability or responsibilty to you or any other person or enfty for any Third-Party Services.</p>

<p>Third-Party Services and links thereto are provided solely 6s @ convenience to you and you access and use them entirely at your own risk and subject to such third paties'terms and conditions.



</p>

                </div>

            </article>

        </div>

    </div>

</div>

</section>
<Footer/>

    </>);
}
export default Privacy;